# 1) Build every commit on every branch and add the COMMIT SHORT SHA as suffix
maven-build:
  stage: build
  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}

# 2) Copies SNAPSHOT builds on 'master' branch into download.dmx.systems/ci/ directory
copy-to-download:
  stage: deploy
  script:
    - CIDIR='/var/www/download.dmx.systems/ci'
    - JARFILE="$( basename $( ls target/*.jar | tail -n1) )"
    - if [ ! -d  ${CIDIR}/${CI_PROJECT_NAME} ]; then mkdir ${CIDIR}/${CI_PROJECT_NAME}; fi
    - cp target/${JARFILE} ${CIDIR}/${CI_PROJECT_NAME}/
  dependencies:
    - maven-build
  only:
    - master
