version: "3.8"

volumes:
  # dmx-db:
  ldap-cfg:
  ldap-db:


services:
  dmx:
    container_name: ${CI_PROJECT_NAME}-dev-dmx-container
    restart: always
    image: container-registry.dmx.systems/dmx-contrib/dmx-docker/dmx-latest:latest
    links:
      - ldap
    environment:
      USER_ID: ${user_id}
      GROUP_ID: ${group_id}
      DMX_ADMIN_PASSWORD: ${DMX_ADMIN_PASSWORD}
      DEEPL_AUTH_KEY: ${DEEPL_AUTH_KEY}
      ## The Nextcloud user used for davfs 
      #NEXTCLOUD_USER: ${NEXTCLOUD_USER}
      #NEXTCLOUD_PASSWORD: ${NEXTCLOUD_PASSWORD}
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_USER_PASSWORD}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      TIER: ${TIER}
    ## for fuse / davfs
    # privileged: true
    #cap_add:
    #  - SYS_ADMIN
    volumes:
      # - dmx-db:/opt/dmx/dmx-db
      - ./instance/dev/conf:/opt/dmx/conf
      - ./instance/dev/logs:/opt/dmx/logs
      - ./instance/dev/db:/opt/dmx/dmx-db
      - ./instance/dev/filedir:/opt/dmx/dmx-filedir
      - ./instance/dev/bundle-deploy:/opt/dmx/bundle-deploy
      - ./dmx/dev/plugins:/opt/dmx/plugins:ro
      - ./dmx/dev/conf.d/config.properties.d:/opt/dmx/conf.d/config.properties.d:ro
      - ./dmx/dev/conf.d/logging.properties.d:/opt/dmx/conf.d/logging.properties.d:ro
    ports:
      - "${DMX_PORT}:8080"


    #networks:
    #  zukunftswerk-dev-network:
    #    ipv4_address: 10.10.10.18

  ldap:
    container_name: ${CI_PROJECT_NAME}-dev-ldap-container
    restart: unless-stopped
    command: "--copy-service --loglevel debug"
    build:
      context: ./ldap/${TIER}
      args:
        LDAP_OPENLDAP_GID: ${user_id}
        LDAP_OPENLDAP_UID: ${group_id}
    environment:
      LDAP_ORGANISATION: "example"
      LDAP_DOMAIN: "example.org"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "bind"
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_USER_PASSWORD}
    ports:
      - "389:389"
      - "636:636"

    #volumes:
      #- ldap-cfg:/etc/ldap/slapd.d
      #- ldap-db:/var/lib/ldap
    #networks:
    #  zukunftswerk-dev-network:
    #    ipv4_address: 10.10.10.19

#  mailhog:
#    container_name: ${CI_PROJECT_NAME}-dev-mailhog-container
#    restart: unless-stopped
#    image: container-registry.dmx.systems/dmx-intern/docker-images/mailhog:latest
#    #networks:
#    #  zukunftswerk-dev-network:
#    #    ipv4_address: 10.10.10.20
#    ports:
#      - "${MAIL_PORT}:8025"


#networks:
#  zukunftswerk-dev-network:
#    driver: bridge
#    internal: false
#    ipam:
#      config:
#        - subnet: 10.10.10.16/28
#          gateway: 10.10.10.17
